---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - serviceaccounts
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kudeploy.com
  resources:
  - buildruns
  - deployments
  - projects
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kudeploy.com
  resources:
  - buildruns/finalizers
  - deployments/finalizers
  - projects/finalizers
  - services/finalizers
  verbs:
  - update
- apiGroups:
  - kudeploy.com
  resources:
  - buildruns/status
  - deployments/status
  - projects/status
  - services/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - tekton.dev
  resources:
  - pipelineruns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
