apiVersion: kudeploy.com/v1alpha1
kind: Service
metadata:
  name: whoami
  namespace: whoami
spec:
  image: ghcr.io/kudeploy/whoami:latest
  env:
    - name: LOG_LEVEL
      value: info
  ports:
    - port: 80
      targetPort: 80
