apiVersion: kudeploy.com/v1alpha1
kind: BuildRun
metadata:
  name: whoami-latest
  namespace: whoami
spec:
  context: .
  dockerfile: ./Dockerfile
  repo:
    url: https://github.com/kudeploy/whoami
  image:
    repository: ghcr.io/kudeploy/whoami
    tag: latest
    secretRef:
      name: image-credentials
